/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fetin_oldhouse;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author igorg
 */
public class Monitoramento extends javax.swing.JFrame {

    /**
     * Creates new form Monitoramento
     */
    String auxu;

    public Monitoramento() {
        setTitle("Monitoramento Inteligente de Asilo v0.1");
        initComponents();

        setExtendedState(MAXIMIZED_BOTH);
        estadoi.setEnabled(false);
        estador6.setEnabled(false);
        casa1.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa1.setHorizontalTextPosition(SwingConstants.CENTER);
        casa2.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa2.setHorizontalTextPosition(SwingConstants.CENTER);
        casa3.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa3.setHorizontalTextPosition(SwingConstants.CENTER);
        casa4.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa4.setHorizontalTextPosition(SwingConstants.CENTER);
        casa5.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa5.setHorizontalTextPosition(SwingConstants.CENTER);
        casa6.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa6.setHorizontalTextPosition(SwingConstants.CENTER);
        casa7.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa7.setHorizontalTextPosition(SwingConstants.CENTER);
        casa8.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa8.setHorizontalTextPosition(SwingConstants.CENTER);
        casa9.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa9.setHorizontalTextPosition(SwingConstants.CENTER);
        casa10.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa10.setHorizontalTextPosition(SwingConstants.CENTER);
        casa11.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa11.setHorizontalTextPosition(SwingConstants.CENTER);
        casa12.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa12.setHorizontalTextPosition(SwingConstants.CENTER);
        casa13.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa13.setHorizontalTextPosition(SwingConstants.CENTER);
        casa14.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa14.setHorizontalTextPosition(SwingConstants.CENTER);
        casa15.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa15.setHorizontalTextPosition(SwingConstants.CENTER);
        casa16.setVerticalTextPosition(SwingConstants.BOTTOM);
        casa16.setHorizontalTextPosition(SwingConstants.CENTER);

    }

    public void listar_idosos(int id) {

        DefaultListModel usu_sel = new DefaultListModel();
        jList1.setModel(usu_sel);
        DAOIdoso daoido = new DAOIdoso();
        ArrayList<Idoso> idosos = daoido.selecionaTodos();
        System.out.println("ID DA CASA: " + id);
        for (Idoso user : idosos) {

            if (user.getCasa() == id) {

                usu_sel.addElement(user.getNome());
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lista = new javax.swing.JButton();
        cadastro = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        dadosi = new javax.swing.JPanel();
        nomei = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rgi = new javax.swing.JFormattedTextField();
        cpfi = new javax.swing.JFormattedTextField();
        cidadei = new javax.swing.JTextField();
        estadoi = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        foto_perfil = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        datai = new javax.swing.JFormattedTextField();
        jLabel59 = new javax.swing.JLabel();
        cidadei1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        obs = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        nomer6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rgr6 = new javax.swing.JFormattedTextField();
        jLabel65 = new javax.swing.JLabel();
        cpfr6 = new javax.swing.JFormattedTextField();
        estador6 = new javax.swing.JComboBox<>();
        jLabel66 = new javax.swing.JLabel();
        cidader6 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        tel6 = new javax.swing.JFormattedTextField();
        jLabel69 = new javax.swing.JLabel();
        datar6 = new javax.swing.JFormattedTextField();
        jLabel70 = new javax.swing.JLabel();
        rua5 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        bairro5 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        num5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        casa1 = new javax.swing.JButton();
        casa2 = new javax.swing.JButton();
        casa3 = new javax.swing.JButton();
        casa4 = new javax.swing.JButton();
        casa5 = new javax.swing.JButton();
        casa6 = new javax.swing.JButton();
        casa7 = new javax.swing.JButton();
        casa8 = new javax.swing.JButton();
        casa9 = new javax.swing.JButton();
        casa10 = new javax.swing.JButton();
        casa11 = new javax.swing.JButton();
        casa12 = new javax.swing.JButton();
        casa13 = new javax.swing.JButton();
        casa14 = new javax.swing.JButton();
        casa15 = new javax.swing.JButton();
        casa16 = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        registros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        lista.setText("Ver Lista de Idosos");
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        cadastro.setText("Cadastrar Idoso");
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        dadosi.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Idoso"));

        nomei.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel2.setText("RG");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel4.setText("Cidade");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setText("Estado");

        rgi.setEditable(false);
        try {
            rgi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU-##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgiActionPerformed(evt);
            }
        });

        cpfi.setEditable(false);
        try {
            cpfi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cidadei.setEditable(false);
        cidadei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeiActionPerformed(evt);
            }
        });

        estadoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        estadoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoiActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        foto_perfil.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        foto_perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto_perfil.setText("Inserir Foto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foto_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel12.setText("Data de Nascimento");

        datai.setEditable(false);
        try {
            datai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel59.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel59.setText("ID do Cartão");

        cidadei1.setEditable(false);
        cidadei1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadei1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações"));

        obs.setEditable(false);
        obs.setColumns(20);
        obs.setRows(5);
        jScrollPane2.setViewportView(obs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dadosiLayout = new javax.swing.GroupLayout(dadosi);
        dadosi.setLayout(dadosiLayout);
        dadosiLayout.setHorizontalGroup(
            dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosiLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(dadosiLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cidadei, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(estadoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dadosiLayout.createSequentialGroup()
                            .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(dadosiLayout.createSequentialGroup()
                                    .addComponent(rgi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cpfi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(nomei))))
                    .addGroup(dadosiLayout.createSequentialGroup()
                        .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosiLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datai, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dadosiLayout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cidadei1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        dadosiLayout.setVerticalGroup(
            dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosiLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cpfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cidadei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(estadoi))
                .addGap(18, 18, 18)
                .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosiLayout.createSequentialGroup()
                        .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(datai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(dadosiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel59)
                            .addComponent(cidadei1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Moradores da Casa"));

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Responsável"));

        nomer6.setEditable(false);
        nomer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomer6ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel14.setText("Nome");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setText("RG");

        rgr6.setEditable(false);
        try {
            rgr6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU-##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgr6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgr6ActionPerformed(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel65.setText("CPF");

        cpfr6.setEditable(false);
        try {
            cpfr6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        estador6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        estador6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estador6ActionPerformed(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel66.setText("Estado");

        cidader6.setEditable(false);
        cidader6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidader6ActionPerformed(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel67.setText("Cidade");

        jLabel68.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel68.setText("Telefone");

        tel6.setEditable(false);
        try {
            tel6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel69.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel69.setText("Data de Nascimento");

        datar6.setEditable(false);
        try {
            datar6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel70.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel70.setText("Rua");

        rua5.setEditable(false);
        rua5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rua5ActionPerformed(evt);
            }
        });

        jLabel71.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel71.setText("Bairro");

        bairro5.setEditable(false);
        bairro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairro5ActionPerformed(evt);
            }
        });

        jLabel72.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel72.setText("Número");

        num5.setEditable(false);
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(rgr6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel65)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cpfr6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nomer6, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel70)
                                    .addComponent(jLabel67))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(cidader6, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel66)
                                        .addGap(18, 18, 18)
                                        .addComponent(estador6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rua5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel71)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairro5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel72)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel68)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel69)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datar6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomer6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rgr6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65)
                    .addComponent(cpfr6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel67)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cidader6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel66))
                    .addComponent(estador6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(rua5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(bairro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(tel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69)
                    .addComponent(datar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mapa do Asilo"));

        casa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa1.setText("Casa 1");
        casa1.setToolTipText("Casa 1");
        casa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa1ActionPerformed(evt);
            }
        });

        casa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa2.setText("Casa 2");
        casa2.setToolTipText("Casa 2");
        casa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa2ActionPerformed(evt);
            }
        });

        casa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa3.setText("Casa 3");
        casa3.setToolTipText("Casa 3");
        casa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa3ActionPerformed(evt);
            }
        });

        casa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa4.setText("Casa 4");
        casa4.setToolTipText("Casa 4");
        casa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa4ActionPerformed(evt);
            }
        });

        casa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa5.setText("Casa 5");
        casa5.setToolTipText("Casa 5");
        casa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa5ActionPerformed(evt);
            }
        });

        casa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa6.setText("Casa 6");
        casa6.setToolTipText("Casa 6");
        casa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa6ActionPerformed(evt);
            }
        });

        casa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa7.setText("Casa 7");
        casa7.setToolTipText("Casa 7");
        casa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa7ActionPerformed(evt);
            }
        });

        casa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa8.setText("Casa 8");
        casa8.setToolTipText("Casa 8");
        casa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa8ActionPerformed(evt);
            }
        });

        casa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa9.setText("Casa 9");
        casa9.setToolTipText("Casa 9");
        casa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa9ActionPerformed(evt);
            }
        });

        casa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa10.setText("Casa 10");
        casa10.setToolTipText("Casa 10");
        casa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa10ActionPerformed(evt);
            }
        });

        casa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa11.setText("Casa 11");
        casa11.setToolTipText("Casa 11");
        casa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa11ActionPerformed(evt);
            }
        });

        casa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa12.setText("Casa 12");
        casa12.setToolTipText("Casa 12");
        casa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa12ActionPerformed(evt);
            }
        });

        casa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa13.setText("Casa 13");
        casa13.setToolTipText("Casa 13");
        casa13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa13ActionPerformed(evt);
            }
        });

        casa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa14.setText("Casa 14");
        casa14.setToolTipText("Casa 14");
        casa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa14ActionPerformed(evt);
            }
        });

        casa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa15.setText("Casa 15");
        casa15.setToolTipText("Casa 15");
        casa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa15ActionPerformed(evt);
            }
        });

        casa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/casinha.png"))); // NOI18N
        casa16.setText("Casa 16");
        casa16.setToolTipText("Casa 16");
        casa16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(casa1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(casa5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(casa9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(casa13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casa16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casa1)
                    .addComponent(casa2)
                    .addComponent(casa3)
                    .addComponent(casa4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casa5)
                    .addComponent(casa6)
                    .addComponent(casa7)
                    .addComponent(casa8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casa9)
                    .addComponent(casa10)
                    .addComponent(casa11)
                    .addComponent(casa12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casa13)
                    .addComponent(casa14)
                    .addComponent(casa15)
                    .addComponent(casa16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel2);

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        registros.setText("Registros");
        registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lista)
                        .addGap(18, 18, 18)
                        .addComponent(cadastro)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(registros)
                        .addGap(18, 18, 18)
                        .addComponent(sair))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casa16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa16ActionPerformed
        listar_idosos(16);
    }//GEN-LAST:event_casa16ActionPerformed

    private void casa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa15ActionPerformed
        listar_idosos(15);
    }//GEN-LAST:event_casa15ActionPerformed

    private void casa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa14ActionPerformed
        listar_idosos(14);
    }//GEN-LAST:event_casa14ActionPerformed

    private void casa13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa13ActionPerformed
        listar_idosos(13);
    }//GEN-LAST:event_casa13ActionPerformed

    private void casa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa12ActionPerformed
        listar_idosos(12);
    }//GEN-LAST:event_casa12ActionPerformed

    private void casa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa11ActionPerformed
        listar_idosos(11);
    }//GEN-LAST:event_casa11ActionPerformed

    private void casa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa10ActionPerformed
        listar_idosos(10);
    }//GEN-LAST:event_casa10ActionPerformed

    private void casa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa9ActionPerformed
        listar_idosos(9);
    }//GEN-LAST:event_casa9ActionPerformed

    private void casa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa8ActionPerformed
        listar_idosos(8);
    }//GEN-LAST:event_casa8ActionPerformed

    private void casa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa7ActionPerformed
        listar_idosos(7);
    }//GEN-LAST:event_casa7ActionPerformed

    private void casa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa6ActionPerformed
        listar_idosos(6);
    }//GEN-LAST:event_casa6ActionPerformed

    private void casa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa5ActionPerformed
        listar_idosos(5);
    }//GEN-LAST:event_casa5ActionPerformed

    private void casa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa4ActionPerformed
        listar_idosos(4);
    }//GEN-LAST:event_casa4ActionPerformed

    private void casa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa3ActionPerformed
        listar_idosos(3);
    }//GEN-LAST:event_casa3ActionPerformed

    private void casa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa2ActionPerformed
        listar_idosos(2);
    }//GEN-LAST:event_casa2ActionPerformed

    private void casa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa1ActionPerformed

        listar_idosos(1);
    }//GEN-LAST:event_casa1ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num5ActionPerformed

    private void bairro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairro5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairro5ActionPerformed

    private void rua5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rua5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rua5ActionPerformed

    private void cidader6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidader6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidader6ActionPerformed

    private void estador6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estador6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estador6ActionPerformed

    private void rgr6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgr6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgr6ActionPerformed

    private void nomer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomer6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomer6ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged

        int x, y;
        DAOIdoso daoido = new DAOIdoso();
        DAOResponsavel daoresp = new DAOResponsavel();
        ArrayList<Idoso> ido = daoido.selecionaTodos();
        ArrayList<Responsavel> resp = daoresp.selecionaTodos();
        auxu = jList1.getSelectedValue();

        for (Idoso user : ido) {

            if (user.getNome().equals(auxu)) {

                nomei.setText(user.getNome());
                cidadei.setText(user.getCidade());
                datai.setText(user.getData_nasc());
                cpfi.setText(user.getCpf());
                rgi.setText(user.getRg());
                obs.setText(user.getObservacoes());
                estadoi.setSelectedItem(user.getEstado());
                if (user.getFoto() == null) {

                } else {

                    File file = new File(user.getFoto());
                    ImageIcon foto = new ImageIcon(file.getPath());
                    Image foto1 = foto.getImage().getScaledInstance(155, 170, Image.SCALE_DEFAULT);
                    foto_perfil.setIcon(new ImageIcon(foto1));
                }

                x = user.getResponsavel_id();
                for (Responsavel user1 : resp) {

                    y = user1.getId_resp();
                    if (x == y) {

                        nomer6.setText(user1.getNome());
                        cidader6.setText(user1.getCidade());
                        bairro5.setText(user1.getBairro());
                        rgr6.setText(user1.getRg());
                        cpfr6.setText(user1.getCpf());
                        rua5.setText(user1.getRua());
                        num5.setText(user1.getNumero());
                        datar6.setText(user1.getData_nasc());
                        tel6.setText(user1.getTelefone());
                        estador6.setSelectedItem(user1.getEstado());
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void cidadei1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadei1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadei1ActionPerformed

    private void estadoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoiActionPerformed

    private void cidadeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeiActionPerformed

    private void rgiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgiActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        Controller C = new Controller();

        dispose();
        C.criarMenu();
    }//GEN-LAST:event_sairActionPerformed

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
        Controller C = new Controller();

            dispose();
            C.criarCadastro_I();
        
    }//GEN-LAST:event_cadastroActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        Controller C = new Controller();

        dispose();
        C.criarLista();

    }//GEN-LAST:event_listaActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
         Controller C = new Controller();
        C.criarPesquisa();
        dispose();
    }//GEN-LAST:event_pesquisarActionPerformed

    private void registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrosActionPerformed
         Controller C = new Controller();
        C.criarRegistro();
        dispose();
    }//GEN-LAST:event_registrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitoramento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro5;
    private javax.swing.JButton cadastro;
    private javax.swing.JButton casa1;
    private javax.swing.JButton casa10;
    private javax.swing.JButton casa11;
    private javax.swing.JButton casa12;
    private javax.swing.JButton casa13;
    private javax.swing.JButton casa14;
    private javax.swing.JButton casa15;
    private javax.swing.JButton casa16;
    private javax.swing.JButton casa2;
    private javax.swing.JButton casa3;
    private javax.swing.JButton casa4;
    private javax.swing.JButton casa5;
    private javax.swing.JButton casa6;
    private javax.swing.JButton casa7;
    private javax.swing.JButton casa8;
    private javax.swing.JButton casa9;
    private javax.swing.JTextField cidadei;
    private javax.swing.JTextField cidadei1;
    private javax.swing.JTextField cidader6;
    private javax.swing.JFormattedTextField cpfi;
    private javax.swing.JFormattedTextField cpfr6;
    private javax.swing.JPanel dadosi;
    private javax.swing.JFormattedTextField datai;
    private javax.swing.JFormattedTextField datar6;
    private javax.swing.JComboBox<String> estadoi;
    private javax.swing.JComboBox<String> estador6;
    private javax.swing.JLabel foto_perfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton lista;
    private javax.swing.JTextField nomei;
    private javax.swing.JTextField nomer6;
    private javax.swing.JTextField num5;
    private javax.swing.JTextArea obs;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton registros;
    private javax.swing.JFormattedTextField rgi;
    private javax.swing.JFormattedTextField rgr6;
    private javax.swing.JTextField rua5;
    private javax.swing.JButton sair;
    private javax.swing.JFormattedTextField tel6;
    // End of variables declaration//GEN-END:variables
}
